/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leleliu008_Foo */

#ifndef _Included_com_leleliu008_Foo
#define _Included_com_leleliu008_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leleliu008_Foo
 * Method:    func1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leleliu008_Foo_func1
  (JNIEnv *, jclass);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leleliu008_Foo_func2
  (JNIEnv *, jobject);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func3
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_leleliu008_Foo_func3
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func4
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_leleliu008_Foo_func4
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func5
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_com_leleliu008_Foo_func5
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func6
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_leleliu008_Foo_func6
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func7
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_leleliu008_Foo_func7
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_leleliu008_Foo_func8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func9
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_leleliu008_Foo_func9
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func10
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_leleliu008_Foo_func10
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func11
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leleliu008_Foo_func11
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_leleliu008_Foo
 * Method:    func12
 * Signature: (Lcom/leleliu008/Foo;)Lcom/leleliu008/Foo;
 */
JNIEXPORT jobject JNICALL Java_com_leleliu008_Foo_func12
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
