/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leleliu008_Foo2 */

#ifndef _Included_com_leleliu008_Foo2
#define _Included_com_leleliu008_Foo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leleliu008_Foo2
 * Method:    func1
 * Signature: ([Z)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_leleliu008_Foo2_func1
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func2
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_leleliu008_Foo2_func2
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func3
 * Signature: ([C)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_leleliu008_Foo2_func3
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func4
 * Signature: ([S)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_leleliu008_Foo2_func4
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func5
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_leleliu008_Foo2_func5
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func6
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_leleliu008_Foo2_func6
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func7
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_leleliu008_Foo2_func7
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func8
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_leleliu008_Foo2_func8
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func9
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo2_func9
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo2
 * Method:    func10
 * Signature: ([Lcom/leleliu008/Foo2;)[Lcom/leleliu008/Foo2;
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo2_func10
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
