/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leleliu008_Foo3 */

#ifndef _Included_com_leleliu008_Foo3
#define _Included_com_leleliu008_Foo3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leleliu008_Foo3
 * Method:    func1
 * Signature: ([[Z)[[Z
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func1
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func2
 * Signature: ([[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func3
 * Signature: ([[C)[[C
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func3
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func4
 * Signature: ([[S)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func4
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func5
 * Signature: ([[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func5
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func6
 * Signature: ([[J)[[J
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func6
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func7
 * Signature: ([[F)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func7
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func8
 * Signature: ([[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func8
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func9
 * Signature: ([[Ljava/lang/String;)[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func9
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_leleliu008_Foo3
 * Method:    func10
 * Signature: ([[Lcom/leleliu008/Foo3;)[[Lcom/leleliu008/Foo3;
 */
JNIEXPORT jobjectArray JNICALL Java_com_leleliu008_Foo3_func10
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
