/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leleliu008_LogTest */

#ifndef _Included_com_leleliu008_LogTest
#define _Included_com_leleliu008_LogTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leleliu008_LogTest
 * Method:    printLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leleliu008_LogTest_printLog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
